### ISSUE TITLE
About NG on ROADMAP.md

### ISSUE THREAD

**Issue by bnb** [nodejs/roadmap#25]
The ROADMAP.md is extremely vague about what NG actually constitutes. Do you have very basic examples of a few things that would happen on the NG build? Also, how often would it be updated? With every push to NG core? Nightly? Following a version of SemVer?

**Comment by mikeal** [comment]
NG is vague because nothing has been decided yet, everything is somewhat up for debate.

The purpose of NG is to have a place where people can work on the "next generation" platform, potentially moving past some of the locked APIs in core today. How that will happen and what it will look like are still very much up for debate and I expect to see some awesome work there soon :)

**Comment by bnb** [comment]
Okay that sounds good. Would you be willing to say something to that effect in ROADMAP.md? I think that's a lot more committal without being actually committal. Essentially, that says to me that we know what we are doing, but just haven't laid everything out yet.

**Comment by jonathanong** [comment]
aside: anyway to test this out, preferably using `nvm`?

**Comment by bnoordhuis** [comment]
Not yet.  I maintain [a next branch](https://github.com/iojs/io.js/commits/next) but no releases have been made yet (because there isn't much to release so far.)

**Comment by Trott** [comment]
Closing all issues in this archived repository.
