### ISSUE TITLE
LTS

### ISSUE THREAD

**Issue by jonathanong** [nodejs/roadmap#45]
any decision on LTS versions? https://github.com/iojs/io.js/issues/1323 bit me in the ass this week, though only momentarily. LTS/master/NG would be great! i'm pinning iojs versions now, and i hate pinning deps.

**Comment by bnoordhuis** [comment]
No decisions have been made as far as I'm aware and I don't think any will be made until we have volunteers and demand for maintaining an LTS branch.  Would-be volunteers should realize that they will be expected to commit for longer periods of time to something that's not very glamorous or fulfilling.

**Comment by rvagg** [comment]
I'll be starting an LTS discussion tomorrow with some initial proposals so we can bikeshed it to death.

But as @bnoordhuis suggested, this is going to likely be driven by people and companies willing to put in a large amount unglamorous, and relatively thankless work. I expect companies like NodeSource and StrongLoop picking up a lot of the slack on this because our commercial interests are very aligned with providing a stable and supported long-term option for companies.

**Comment by mikeal** [comment]
Can we feed this LTS work in to the foundation dev policy https://github.com/jasnell/dev-policy to reduce overlap.

If we don't end up reconciling we can just take the LTS portion out and adopt it in io.js.

**Comment by rvagg** [comment]
See https://github.com/iojs/io.js/issues/1346 pointing to discussion starters in https://github.com/iojs/LTS

Sorry @mikeal, I'm really after discussion at this point rather than concrete proposals. I'd love to get an LTS WG started to come up with the initial policies and start experimenting with making an LTS work. I'm a bit -1 on holding this up in the hope of a reconciliation because that could take a _very long time_, if it happens at all.

I'm also not sure why LTS needs to be part of an initial dev-policy proposal for a Foundation, it seems premature to bake that in. If it makes sense though it'd be great if discussion that happens fed into your work there though.

**Comment by mikeal** [comment]
> I'm also not sure why LTS needs to be part of an initial dev-policy proposal for a Foundation

Well, a merged project would *immediately* have LTS lines it needs to deal with and release, that's why it makes sense to work on it in the dev policy. That said, the LTS dev policy *is* totally different from the main dev policy for current releases.

Anyway, I think you're right, we have a structure (io.js working groups) to flush this out in today and depending on how long reconciliation takes we could need LTS releases of io.js so we'll need something in place.

> it seems premature to bake that in

The whole dev policy is a living document we're expected to iterate on it. The LTS sections of the dev policy say "this is owned by the LTS WG" rather than the main TSC.

**Comment by TheAlphaNerd** [comment]
Since we officially have LTS now can this be closed?

**Comment by jasnell** [comment]
yep. I'd say so
